export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS'
export const GET_CATEGORIES_FAILURE = 'GET_CATEGORIES_FAILURE'
export const GET_CATEGORIES_ISLOADING = 'GET_CATEGORIES_ISLOADING'
export const SET_SELECTED_CATEGORY = 'SET_SELECTED_CATEGORY'
