export const GET_CURRENCIES_SUCCESS = 'GET_CURRENCIES_SUCCESS'
export const GET_CURRENCIES_FAILURE = 'GET_CURRENCIES_FAILURE'
export const GET_CURRENCIES_ISLOADING = 'GET_CURRENCIES_ISLOADING'
export const SET_SELECTED_CURRENCY = 'SET_SELECTED_CURRENCY'
